[package]
name = "polymoly-cli"
version = "0.1.0"
edition = "2021"
default-run = "polymoly"

[[bin]]
name = "polymoly"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
polymoly = { path = ".."}
